import { Navbar } from "@/components/layout/navbar";
import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css"
import { SideBar } from "@/components/layout/sidebar";
import { ChatProvider  } from "../context/ChatContext";


const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico", // for Tailwind
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
  return (
    <html lang="en"  className={pacifico.variable}>
        <head>
            <link href="https://fonts.googleapis.com/css2?family=Ancizar+Sans:ital,wght@0,100..1000;1,100..1000&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Pacifico&display=swap" rel="stylesheet"></link>
        </head>
        
      <body
        className='font-[Inter] text-[#242424]'
      >
        <Navbar />
          <ChatProvider>
          <div className="flex">
            <SideBar />
            {children}
          </div>
        </ChatProvider>
      </body>
    </html>
  );
}
